<?php

/*
|--------------------------------------------------------------------------
| Disclaimer Strings
|--------------------------------------------------------------------------
|
| Single source of truth for the demo/legal disclaimer text, consumed by
| App\Domain\Disclaimers\DisclaimerText. Canonical wording lives in
| docs/legal/TERMS-AND-DISCLAIMER.md — edit there first, then mirror the
| change here.
|
*/

return [

    'short' => [
        'en' => 'DEMO PROJECT — NOT MEDICAL ADVICE',
        'pl' => 'PROJEKT DEMONSTRACYJNY — TO NIE JEST PORADA MEDYCZNA',
    ],

    'standard' => [
        'en' => 'Demo project. This plan was generated by simple hard-coded rules, not by a '
            .'dietitian or trainer, and is not medical or nutritional advice. Consult a '
            .'qualified professional before changing your diet or training.',
        'pl' => 'Projekt demonstracyjny. Ten plan został wygenerowany przez proste, z góry '
            .'zdefiniowane reguły, a nie przez dietetyka czy trenera, i nie jest poradą '
            .'medyczną ani żywieniową. Przed zmianą diety lub treningu skonsultuj się z '
            .'wykwalifikowanym specjalistą.',
    ],

    'extended' => [
        'en' => 'FitnessLab is a free demonstration project built to showcase software '
            .'engineering practice. Its author is not a dietitian, nutritionist, or '
            .'certified trainer. Nothing here is medical advice — consult a qualified '
            .'professional before acting on any of it.',
        'pl' => 'FitnessLab to bezpłatny projekt demonstracyjny, zbudowany po to, by pokazać '
            .'warsztat programistyczny. Jego autor nie jest dietetykiem, specjalistą do '
            .'spraw żywienia ani certyfikowanym trenerem. Nic tutaj nie jest poradą '
            .'medyczną — przed podjęciem jakichkolwiek działań skonsultuj się z '
            .'wykwalifikowanym specjalistą.',
    ],

];
